
method: robustlt_atbsl
method_opt:
  tau_b: 1.0
  label_smoothing: 0.
  robustlt_alpha: 0.3
  robustlt_beta: 0.8

# dataset
data: cifar10lf
augment: aua
imbalance_rate: 50

# model
model: wrn-28-10
classifier: FC
classifier_opt: ~

# optimizer
batch_size: 128
batch_size_validation: 128
num_epochs: 100
lr: 0.1
scheduler: step
scheduler_opt:
  gamma: 0.1
  milestones:
    - 75
    - 90

