
method: robal
method_opt:
  m: 0.1
  s: 10
  tau_b: 1.5
  tau_m: 0.3
  beta: 6.0
  beta_adv: 1.0

# dataset
augment: base
data: tinylf
imbalance_rate: 10

# model
model: wrn-28-10
classifier: CosPlus
classifier_opt:
  bias: False
  posthoc: False
  gamma: 0.03125
  scale: 1

# optimizer
num_epochs: 80
lr: 0.1
batch_size: 64
test_batch_size: 64
scheduler: step
scheduler_opt:
  gamma: 0.1
  milestones:
    - 60
    - 75
attack_iter: 5


